apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
spec:
  selector:
    app: ml-model  # This MUST match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80         # The port the public sees
      targetPort: 8080 # The port your Python app (FastAPI) is listening on
  type: LoadBalancer   # This tells the cloud to give you a Public IP address